# Generated by Django 5.0.2 on 2024-03-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmgmtsys', '0002_alter_enrollment_mark_alter_student_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enroll_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
