# Generated by Django 5.0.2 on 2024-03-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmgmtsys', '0004_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='reserve1',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='reserve2',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='reserve3',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='reserve4',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='stage',
        ),
        migrations.AddField(
            model_name='setting',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
