# Generated by Django 5.0.2 on 2024-03-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(default='report', max_length=128),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(null=True),
        ),
    ]
