# Generated by Django 5.0.2 on 2024-03-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsapp', '0003_alter_report_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='onecard',
            name='issued_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
